### ISSUE TITLE
Схема данных

### ISSUE THREAD

**Issue by basavind** [kotofun/Junkyard#1]
Раздел "Типы данных" https://kursomir.github.io/Transfer/

**Comment by ZverArt** [comment]
Если что, готов помочь.

**Comment by ZverArt** [comment]
@mixty1 ты чо, охренел? :-D

**Comment by ZverArt** [comment]
Сделано

**Comment by ZverArt** [comment]
![erd](https://cloud.githubusercontent.com/assets/10755414/24582791/b2a48cd0-1737-11e7-889a-453f40e815fe.png)
Передаём эстафету @mixty1 :)

**Comment by basavind** [comment]
забыли у материалов и слайсов таймстампы created_at и updated_at

**Comment by mixty1** [comment]
таймстампы всё-равно автоматом везде добавляются

**Comment by basavind** [comment]
Но это не означает, что они нужны везде :)

**Comment by mixty1** [comment]
Не означает, но почему бы везде их не ставить, это позволит сортировать по дате добавления и изменения.

**Comment by basavind** [comment]
Рейтинги, типы слайсов, лицензии, владельцев, статусы и прочее не надо сортировать по дате добавления и редактирования. @zverart @agareev вообще мнение по этому поводу?

**Comment by ZverArt** [comment]
Если они создаются автоматически и их убрать нельзя, то пусть будут, но просто не будем их использовать там, где это не указано в нашей модели данных.

Если можно удалить — то удаляем. По модели прошлись несколько раз, там Timestamp не нужны

**Comment by mixty1** [comment]
А вдруг будет нужда в сортировке по дате. Ну я лично их не убирал бы, они как-то и не мешают, вдруг пригодятся. Если уж они прям так смущают, то окей, не будем добавлять, там, где не нужны.

**Comment by ZverArt** [comment]
Я просто не могу представить use-case, когда нам нужна будет сортировка по дате)

**Comment by mixty1** [comment]
Вот тупо в админке нужно будет тебе вывести список юзеров и отсортировать их по дате когда они регались, или где-то в профиле нужно выводить дату регистрации и в таком духе

**Comment by ZverArt** [comment]
@mixty1 не, погоди. Давай начнём с того, что таблица юзера здесь сейчас минимальная. Этого недостаточно, чтобы полностью запустить ту же платформу, например. Таблица в дальнейшем будет расширена.

**Comment by basavind** [comment]
В юзерах я бы тоже оставил, но во всех вспомогательных табличках нафиг повыпиливал

**Comment by basavind** [comment]
И не стоит забывать, что данные в бд - это все-таки осмысленный стейт а не свалка всего подряд

**Comment by mixty1** [comment]
Просто в дальнейшем если вдруг понадобятся таймстэмпы, то у тех данных, которые были до того, как добавили эти таймстэмпы, их не будет или будут даты какие-то по умолчанию, то смысл уже теряется.

**Comment by mixty1** [comment]
Короче я предупреждал :D

**Comment by ZverArt** [comment]
Ну окей, с юзерами хорошо. Я всё ещё не вижу применения этим данным (зачем мне сортировать юзеров?), но предположим на случай краша системы и чтобы понять с какой даты у нас пропали данные. Окей.

Но по остальному да, Дима прав.

**Comment by basavind** [comment]
В общем таймстампы **нужны** у `materials`, `users`, `translations`, `comments`.

`slices` и `rates` — не уверен в надобности, но возможно есть какой-то смысл в дальнейшем отображать дату рейтингования тем или иным человеком можно оставить таймстампы прозапас.

Таймстампы **точно не нужны** у `licenses`, `owners`, `states`, `material_tags`, `slice_types`

**Comment by mixty1** [comment]
Кстати еще момент. Нет пометок, что поле обязательное или нет (NULL/NOT NULL) и если обязательное, то значение по умолчанию какое-то. В том же rubocop есть проверка на это - [rails not null column](http://rubocop.readthedocs.io/en/latest/cops_rails/#railsnotnullcolumn) (можно и отключить)

**Comment by agareev** [comment]
Я очень советую оставить таймстампы везде где только можно. Вдруг пригодятся. Места много не занимают.

**Comment by basavind** [comment]
![erd](https://cloud.githubusercontent.com/assets/1267239/24601010/eba0e1cc-185f-11e7-9ee4-d8eea5e221cc.png)


Везде подряд ставить таймстампы не надо. Конечный вариант. В колонке `N` если стоит +, то поле может принимать NULL, во всех остальных случаях — NOT NULL, где возможны значения по-умолчанию, там указано в колонке D. Все остальные ограничения являются бизнес-логикой и не должны забиваться мусор лишь для создания сущности.

**Comment by ZverArt** [comment]
Про null-то мы и забыли))) Вообще, предлагаю в materials сделать ещё not null caption_original. А вот annotation_translated сделать null, так как не факт, что у материала есть аннотация

**Comment by basavind** [comment]
Читай внимательней - если плюсика нет, то поле not null, если плюсик есть, то поле может принимать null . Символ N в схеме расшифровывается как Nullable.

**Comment by basavind** [comment]
![erd 1](https://cloud.githubusercontent.com/assets/1267239/24617620/14fa8644-189d-11e7-9e2e-f2feb30b3fa0.png)

Еще пару косяков поправил, теперь вроде конечный вариант ))

**Comment by mixty1** [comment]
если поле обязательное, но по умолчанию ничего нет, то ставить просто пустую строчку, а если тип целое число или булевое, то 0 и false соответственно или вообще ничего не ставить?

**Comment by basavind** [comment]
Если поле обязательное, но по-умолчанию ничего нет, то ничего не ставить не надо - бросай исключение и пусть пользователь вносит все необходимые данные. Для этого и нужны constraints в бд.

**Comment by mixty1** [comment]
Объясните мне почему у material_tags есть name и display_name, ладно со вторым ясно, а первое для чего и почему body в json, а не массив или что body вообще делает если есть display_name? Зачем тогда вообще отдельная сущность под теги, если есть массив у материалов под теги?

**Comment by basavind** [comment]
Для этого стоит глянуть схему апи. Если в кратце name - слаг, который удобно использовать в коде, без пробелов на латинице и прочее. Display_name - то, как тег отображается в интерфейсе, например "раздел науки". В body json - для различных типов тегов, пока что для переводимых и непереводимых, например раздел науки может быть computer science / информатика, тогда тег будет выглядеть "раздел науки: информатика" или "раздел науки: computer science", что по факту будет одним тегом. Конечно можно добавить поле для display_name с привязкой к языку, но пока думаю достаточно будет тегов на одном языке. Массив в постгрес хранит вроде только скалярные типы, поэтому в нем можно хранить только айдишники тегов. Можно поле tags у материалов выбросить, но тогда необходимо добавлять новую таблицу(сущность) для связи многие-ко-многим. Но мне кажется пока массива с айдишниками нам хватит на достаточно долгое время.

**Comment by mixty1** [comment]
Надо бы поправить схему, там где массивы, вместо array, делать так: тип[] (integer[], string[]).
Там где предполагается строка больше чем 255 символов, то тип ставить Text.

**Comment by mixty1** [comment]
еще маленький косячок в materials, в столбике D у поля state_id, прописано import_id

**Comment by basavind** [comment]
По поводу `materials`.`state_id` — до сидирования таблиц не известны айдишки у стейтов, соответственно нет возможности вписать айди, который будет соответствовать стейту `import`. Если у стейта `import` будет айди 1, то по-умолчанию в `materials`.`state_id` будет 1.

Остальное сейчас поправлю.

**Comment by basavind** [comment]
Вроде всё что попалось на глаз поправил.

![erd 2](https://cloud.githubusercontent.com/assets/1267239/24626785/1842ea4e-18bb-11e7-858f-510ed2357506.png)

**Comment by basavind** [comment]
Апдейтнул схему данных (`slice` => `chunk`, `slice_type` => `chunk_type`) и связи в другой нотации сделал.

![erd 1](https://cloud.githubusercontent.com/assets/1267239/25063509/9c763316-21ee-11e7-99b7-fa0aedb7a151.png)
